name: Contributor Takes Action
on:
  issue_comment:
    types: [created]

jobs:
  assign_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign issue to contributor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BODY="${{ github.event.comment.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          LOGIN="${{ github.event.comment.user.login }}"
          REPO="${{ github.repository }}"
          ISSUE_LABELS=$(echo "${{ toJson(github.event.issue.labels.*.name) }}")
          ISSUE_CURRENTLY_ASSIGNED=$(jq -n '${{ toJson(github.event.issue.assignees) | length == 0 }}')
          GOOD_FIRST_ISSUE_LABEL="good first issue"
          GOOD_FIRST_ISSUE=$(echo "$ISSUE_LABELS" | grep -w "$GOOD_FIRST_ISSUE_LABEL")

          # Check if the user has previously been assigned to a good first issue
          HAS_PREVIOUSLY_CONTRIBUTED=$(curl -H "Authorization: bearer $GITHUB_TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+assignee:$LOGIN+label:\"$GOOD_FIRST_ISSUE_LABEL\"+is:issue+state:closed" | jq '.total_count != 0')

          if [[ "$BODY" == *"${{ inputs.trigger }}"* ]]; then
            if [[ "$ISSUE_CURRENTLY_ASSIGNED" == "true" ]]; then
              if [ ! -z "$GOOD_FIRST_ISSUE" ] && [ "$HAS_PREVIOUSLY_CONTRIBUTED" == "true" ]; then
                echo "This user has already been assigned to a good first issue. Not assigning again."
                exit 0
              fi
              BLOCKING_LABELS=$(echo "${{ inputs.blockingLabels }}" | jq -n --arg str "${{ inputs.blockingLabels }}" '$str | split(",")')
              echo "Issue labels: $ISSUE_LABELS"
              echo "Blocking labels: $BLOCKING_LABELS"
              blocking_label_found=$(jq -n --argjson ISSUE_LABELS "$ISSUE_LABELS" --argjson BLOCKING_LABELS "$BLOCKING_LABELS" '$ISSUE_LABELS as $il | $BLOCKING_LABELS as $bl | any($il[]; . as $i | any($bl[]; . == $i))')
              echo "blocking label found: $blocking_label_found"
              if [ "$blocking_label_found" == "true" ]; then
                echo "Issue contains one or more blocking labels: $BLOCKING_LABELS"
                echo "Unable to assign issue $ISSUE_NUMBER to $LOGIN"
                if [[ ! -z "${{ inputs.blockingLabelsMessage }}" ]]; then
                  jq -n -r --arg body "${{ inputs.blockingLabelsMessage }}" '{body: $body}' > payload.json
                  curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" --data @payload.json https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments
                fi
              else
                echo "Assigning issue $ISSUE_NUMBER to $LOGIN"
                curl -H "Authorization: bearer $GITHUB_TOKEN" -d '{"assignees":["'"$LOGIN"'"]}' https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/assignees
                if [[ ! -z "${{ inputs.message }}" ]]; then
                  jq -n -r --arg body "${{ inputs.message }}" '{body: $body}' > payload.json
                  curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" --data @payload.json https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments
                fi
              fi
            else
              echo "This issue is currently assigned to a different user"
              if [[ ! -z "${{ inputs.issueCurrentlyAssignedMessage }}" ]]; then
                jq -n -r --arg body "${{ inputs.issueCurrentlyAssignedMessage }}" '{body: $body}' > payload.json
                curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" --data @payload.json https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments
              fi
            fi
          fi
        inputs:
          message:
            description: 'Message to prospective contributor'
            required: false
            default: ''
          issueCurrentlyAssignedMessage:
            description: 'Message to contributors if issue is already assigned'
            required: false
            default: 'The issue you are trying to assign to yourself is already assigned.'
          blockingLabels:
            description: 'Optional labels that are on an issue that block an issue from being assigned by the trigger.'
            required: false
            default: ''
          blockingLabelsMessage:
            description: 'Message to contributors if issue is blocked by a label'
            required: false
            default: 'The issue you are trying to assign to yourself is blocked by a one or more labels on the issue.'
          trigger:
            description: 'The string that triggers the action'
            required: false
            default: '.take'
          token:
            description: 'The GitHub PAT used to authenticate when updating the Issue'
            required: true
