name: contributor-takes-action
on:
  issue_comment:
    types: [created]

jobs:
  assign-if-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign issue to new contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetching issue and comment details
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          COMMENTER=$(jq --raw-output .comment.user.login "$GITHUB_EVENT_PATH")
          REPO_FULL_NAME=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")
          # Function to check if the user has previous contributions
          function has_contributed() {
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_FULL_NAME/commits?author=$1")
            TOTAL_COUNT=$(echo "$RESPONSE" | jq -r '. | length')
            if [[ "$TOTAL_COUNT" -gt 0 ]]; then
              echo "true"
            else
              echo "false"
            fi
          }
          # Check if the user has already contributed
          HAS_CONTRIBUTED=$(has_contributed $COMMENTER)
          # Logic to assign the issue or not based on previous contributions
          if [[ "$HAS_CONTRIBUTED" == "true" ]]; then
            # User has contributed before, do not assign
            MESSAGE="Thank you for your interest, but as a previous contributor, we are reserving this issue for new contributors."
            echo "$MESSAGE"
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -X POST -d "{\"body\": \"$MESSAGE\"}" \
                 "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/comments"
          else
            # User has not contributed before, assign the issue
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -X POST -d "{\"assignees\": [\"$COMMENTER\"]}" \
                 "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/assignees"
            MESSAGE="You have been assigned to this issue. Thanks for your contribution!"
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -X POST -d "{\"body\": \"$MESSAGE\"}" \
                 "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/comments"
          fi
