name: Assign issue to contributor
on:
  issue_comment:
    types: [created]

jobs:
  assign:
    name: Take an issue
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract issue and user information and check comment
      run: |
        COMMENT_BODY=$(jq --raw-output .comment.body "$GITHUB_EVENT_PATH")
        echo "Received comment: '${COMMENT_BODY}'"
        if [[ "$COMMENT_BODY" != ".take" ]]; then
          echo "Comment does not contain '.take', exiting..."
          exit 0
        fi
        echo "Comment contains '.take', proceeding..."

        COMMENTER=$(jq --raw-output .comment.user.login "$GITHUB_EVENT_PATH")
        REPO_FULL_NAME=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")
        ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
        
        echo "Proceeding with user: $COMMENTER on issue $ISSUE_NUMBER in repo $REPO_FULL_NAME"

    - name: Fetch issue labels and check contributor status
      run: |
        # Fetch issue labels
        LABELS_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/labels")
        echo "Labels response: $LABELS_RESPONSE"
        HAS_GOOD_FIRST_ISSUE_LABEL=$(echo "$LABELS_RESPONSE" | jq 'if type == "array" then map(select(.name == "good first issue")) | length else 0 end')
        echo "Good first issue label presence: $HAS_GOOD_FIRST_ISSUE_LABEL"

        # Check for previous contributions
        CONTRIBUTIONS_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO_FULL_NAME/commits?author=$COMMENTER")
        echo "Contributions response: $CONTRIBUTIONS_RESPONSE"
        HAS_CONTRIBUTED=$(echo "$CONTRIBUTIONS_RESPONSE" | jq '. | length > 0')
        echo "Contributed: $HAS_CONTRIBUTED"

    - name: Assign issue based on conditions
      run: |
        echo "Evaluating conditions to assign the issue..."
        if [[ "$HAS_CONTRIBUTED" == "true" && "$HAS_GOOD_FIRST_ISSUE_LABEL" == "0" ]] || [[ "$HAS_CONTRIBUTED" == "false" ]]; then
          MESSAGE="This issue is now assigned to you. Thank you for your contributions!"
          echo $MESSAGE
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\": \"$MESSAGE\"}" "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/comments"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"assignees\": [\"$COMMENTER\"]}" "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/assignees"
        else
          MESSAGE="Thank you for your interest, but this 'good first issue' is reserved for new contributors."
          echo $MESSAGE
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\": \"$MESSAGE\"}" "https://api.github.com/repos/$REPO_FULL_NAME/issues/$ISSUE_NUMBER/comments"
        fi
